apiVersion: apps/v1
kind: Deployment
metadata:
  name: campvista-deployment
  namespace: campvista
  labels:
    app: campvista
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campvista
  template:
    metadata:
      labels:
        app: campvista
    spec:
      containers:
        - name: campvista
          image: rohitar/campvista:CV3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "50m"
              memory: "64Mi"
            requests:
              cpu: "25m"
              memory: "32Mi"
