apiVersion: v1
kind: Service
metadata:
  name: campvista-service
  namespace: campvista
spec:
  type: NodePort  
  selector:
    app: campvista
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
