apiVersion: v1
kind: Service
metadata:
  name: campvista-service
  namespace: campvista
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"   # or "elb" for classic LB
spec:
  type: LoadBalancer
  selector:
    app: campvista
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
